// Generates DBZKit/Legacy/OpcodeDocs.xml -- a C#-XML-doc-comment-shaped file
// (same <doc><members><member name="..."><summary>/<param> shape .NET emits
// for its own XML doc comments) consumed at runtime by OpcodeDocs.cs to power
// the Legacy_IDE editor's Ctrl+Space autocomplete descriptions and hover/call-tip
// hints. Source of truth is opcode_data.js (same OPS array gen_wiki.js uses to
// write the Legacy.wiki opcode pages), so this file and the wiki never drift
// out of sync with each other -- regenerate both from the same edit.
const fs = require('fs');
const path = require('path');
const { OPS } = require('./opcode_data');

function xmlEscape(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// Strip markdown emphasis/backticks and collapse to plain text for a tooltip-friendly summary.
function plainText(s) {
  return String(s)
    .replace(/\*\*/g, '')
    .replace(/`([^`]*)`/g, '$1')
    .trim();
}

function firstSentence(remarks) {
  const masked = remarks.replace(/`[^`]*`/g, s => s.replace(/\./g, ' '));
  let cut = masked.indexOf('. ');
  if (cut === -1) cut = masked.length - 1;
  return plainText(remarks.slice(0, cut + 1));
}

const members = [];

// The three Jump-family pseudo-ops aren't Step-table opcodes (see Zenkai-wiki
// control-flow/jump-family.md) so they're not in OPS -- documented by hand here,
// kept in sync manually since there are only three and they're stable.
members.push({
  name: 'Jump', arity: 1, confidence: 'confirmed',
  summary: 'Unconditionally branches to a label. Operand is a signed byte relative to the address immediately after the operand.',
  params: [{ name: 'offset', desc: 'Label to jump to.' }],
});
members.push({
  name: 'JumpIfFalse', arity: 1, confidence: 'confirmed',
  summary: 'Pops the top of the VM stack; if falsy, branches to a label the same way Jump does. If truthy, execution continues to the next instruction.',
  params: [{ name: 'offset', desc: 'Label to jump to if the popped condition is falsy.' }],
});
members.push({
  name: 'LoopOrJump', arity: 1, confidence: 'confirmed',
  summary: 'Decrement-and-branch loop primitive (not a plain jump). Decrements a per-nesting-depth loop counter; branches backward to the label until the counter reaches 1, then falls through.',
  params: [{ name: 'offset', desc: 'Label at the top of the loop body to branch back to.' }],
});

for (const op of OPS) {
  const [index, rawName, category, args, pushes, remarks, confidence] = op;
  if (!rawName || !remarks) continue; // skip dedup placeholders (PlayMusic@49, SpawnItem@92)

  const displayName = rawName.replace(/^BytecodeVM_|^Bytecode_/, '');
  let summary = firstSentence(remarks);
  if (pushes) summary += ` Pushes ${plainText(pushes)} onto the VM stack.`;
  if (confidence === 'low') summary = '[Low confidence] ' + summary;

  members.push({
    name: displayName,
    originalName: rawName,
    index,
    arity: args.length,
    confidence,
    summary,
    params: args.map(a => ({ name: a.n, desc: plainText(a.d) })),
  });
}

const lines = [];
lines.push('<?xml version="1.0" encoding="utf-8"?>');
lines.push('<!-- AUTO-GENERATED by DBZKit/gen_opcode_xml.js from DBZKit/opcode_data.js. Do not hand-edit -- regenerate instead. -->');
lines.push('<doc>');
lines.push('  <assembly><name>Zenkai</name></assembly>');
lines.push('  <members>');
for (const m of members) {
  const attrs = [`name="${xmlEscape(m.name)}"`, `arity="${m.arity}"`, `confidence="${xmlEscape(m.confidence)}"`];
  if (m.originalName && m.originalName !== m.name) attrs.push(`originalName="${xmlEscape(m.originalName)}"`);
  if (m.index !== undefined) attrs.push(`index="${m.index}"`);
  lines.push(`    <member ${attrs.join(' ')}>`);
  lines.push(`      <summary>${xmlEscape(m.summary)}</summary>`);
  for (const p of m.params)
    lines.push(`      <param name="${xmlEscape(p.name)}">${xmlEscape(p.desc)}</param>`);
  lines.push('    </member>');
}
lines.push('  </members>');
lines.push('</doc>');

const outPath = path.join(__dirname, 'Legacy', 'OpcodeDocs.xml');
fs.writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
console.log(`Wrote ${members.length} opcode doc entries to ${outPath}`);
