// BytecodeVM_OpcodeTable -- 0x083B5D28, 145 entries (indexes are the operand byte of main opcode 0x02 "Step" and of the StepTypePost_* opcodes).
// HIGH: the handler addresses were read from the ROM; see each action's file for its own address and certainty. Slots 87 and 92 share one function.
#include "dbzlog2/vm/actions.h"

namespace dbzlog2::vm {

const ActionHandler g_BytecodeVM_OpcodeTableImpl[kActionCount] = {
    BytecodeVM_PushAccumulator,   // 0
    BytecodeVM_PushGlobalVar0,   // 1
    BytecodeVM_PushGlobalVar1,   // 2
    BytecodeVM_PushGlobalVar2,   // 3
    BytecodeVM_PushScriptArg0,   // 4
    BytecodeVM_PushScriptArg1,   // 5
    BytecodeVM_PushScriptArg2,   // 6
    BytecodeVM_PushScriptArg3,   // 7
    BytecodeVM_PushCurrentWorld,   // 8
    BytecodeVM_PushCurrentArea,   // 9
    BytecodeVM_PushCurrentVariant,   // 10
    BytecodeVM_PushActiveCharIndex,   // 11
    BytecodeVM_PushActiveCharName,   // 12
    BytecodeVM_PushActiveCharHP,   // 13
    BytecodeVM_PushActiveCharMaxHP,   // 14
    BytecodeVM_PushActiveCharEP,   // 15
    BytecodeVM_PushActiveCharMaxEP,   // 16
    BytecodeVM_StackRand,   // 17
    BytecodeVM_StackRandChance,   // 18
    BytecodeVM_StackTestStoryFlag,   // 19
    BytecodeVM_StackTestStoryFlagNot,   // 20
    BytecodeVM_StackGetItemCount,   // 21
    BytecodeVM_StackGetCharLevel,   // 22
    BytecodeVM_StackTestPartyMemberFlag,   // 23
    BytecodeVM_DisableLayer,   // 24
    BytecodeVM_EnableLayer,   // 25
    BytecodeVM_PickUpItem,   // 26
    BytecodeVM_SetStoryFlag,   // 27
    BytecodeVM_ClearStoryFlag,   // 28
    BytecodeVM_FindCharacterEntity,   // 29
    BytecodeVM_FindEntityByType,   // 30
    BytecodeVM_ShowChoicePrompt,   // 31
    BytecodeVM_CenterCameraOnChar,   // 32
    BytecodeVM_SetActiveEntity,   // 33
    BytecodeVM_SetMapRestoreFlag,   // 34
    BytecodeVM_LoadMapWithEntities,   // 35
    BytecodeVM_LoadMapNoEntities,   // 36
    BytecodeVM_RestoreMap,   // 37
    BytecodeVM_WarpToMapWithEntities,   // 38
    BytecodeVM_WarpToMapNoEntities,   // 39
    BytecodeVM_FadeOut,   // 40
    BytecodeVM_FadeFromWhite,   // 41
    BytecodeVM_FadeToWhite,   // 42
    BytecodeVM_TimedSceneWait_A,   // 43
    BytecodeVM_TimedSceneWait_B,   // 44
    BytecodeVM_UploadSpritePalette,   // 45
    BytecodeVM_PlayAudio,   // 46
    BytecodeVM_StopAudio,   // 47
    BytecodeVM_StopAllAudio,   // 48
    BytecodeVM_PlayMusic,   // 49
    BytecodeVM_StopMusic,   // 50
    BytecodeVM_SpawnCharacterEntity,   // 51
    BytecodeVM_DespawnEntity,   // 52
    BytecodeVM_WalkToPosition,   // 53
    BytecodeVM_FlyToPosition,   // 54
    BytecodeVM_SetEntityFacing,   // 55
    BytecodeVM_SetEntityFollow,   // 56
    BytecodeVM_SetEntityAnimation,   // 57
    BytecodeVM_EntityWaitFrames,   // 58
    BytecodeVM_Deprecated_CharacterSpecialAttack,   // 59
    BytecodeVM_EntityCmd_8025258,   // 60
    BytecodeVM_Deprecated_CharacterFollow,   // 61
    BytecodeVM_SetEntityPositionInstant,   // 62
    BytecodeVM_BeginCommandBatch,   // 63
    BytecodeVM_CommitCommandBatch,   // 64
    BytecodeVM_PlayAudioBlocking,   // 65
    BytecodeVM_Deprecated_ShowImage,   // 66
    BytecodeVM_RunFixedScreen_60,   // 67
    BytecodeVM_WaitFramesSimple,   // 68
    BytecodeVM_WaitFrames,   // 69
    BytecodeVM_SetActiveCharacter,   // 70
    BytecodeVM_SetCollisionRect,   // 71
    BytecodeVM_ClearCollisionRect,   // 72
    BytecodeVM_SetCharacterTransformation,   // 73
    BytecodeVM_ReloadMap,   // 74
    BytecodeVM_PushActiveCharNameUpper,   // 75
    BytecodeVM_RemoveItem,   // 76
    BytecodeVM_RemoveItems,   // 77
    BytecodeVM_SetBgLayerPriority,   // 78
    BytecodeVM_SetCharacterInPartyFlag,   // 79
    BytecodeVM_SetCharacterFlag_Bit1,   // 80
    BytecodeVM_ClearCharacterFlag_Bit1,   // 81
    BytecodeVM_SetCharacterFlag_Bit5,   // 82
    BytecodeVM_SetCharacterFlag_Dynamic,   // 83
    BytecodeVM_TriggerMapEvent,   // 84
    BytecodeVM_FadeIn,   // 85
    BytecodeVM_SetPlayerVisible,   // 86
    BytecodeVM_SpawnItem,   // 87
    BytecodeVM_FindEntityType16,   // 88
    BytecodeVM_EntityCmd_801094C_Link,   // 89
    BytecodeVM_SpawnEntityForChar_80104C0,   // 90
    BytecodeVM_ClearCharacterInPartyFlag,   // 91
    BytecodeVM_SpawnItem,   // 92
    BytecodeVM_EntityStopMovement,   // 93
    BytecodeVM_EntitySetVelocity,   // 94
    BytecodeVM_EntityCmd_8024DD0,   // 95
    BytecodeVM_EntityCmd_8025514_Toward,   // 96
    BytecodeVM_ReturnToTitleScreen,   // 97
    BytecodeVM_SetCharacterLevel,   // 98
    BytecodeVM_EntityCmd_8024A50_Arc,   // 99
    BytecodeVM_EntityCmd_8025230_2arg,   // 100
    BytecodeVM_SpawnTileEntity_A,   // 101
    BytecodeVM_SpawnTileEntity_B,   // 102
    BytecodeVM_SpawnEntity4Arg,   // 103
    BytecodeVM_DespawnCharacterAndRecordPosition,   // 104
    BytecodeVM_StackGetCharHP,   // 105
    BytecodeVM_StackGetCharEP,   // 106
    BytecodeVM_StackGetCharMaxHP,   // 107
    BytecodeVM_StackGetCharMaxEP,   // 108
    BytecodeVM_SetCharHP,   // 109
    BytecodeVM_SetCharEP,   // 110
    BytecodeVM_PlayAudioVolume,   // 111
    BytecodeVM_EntityCmd_8025244_1arg,   // 112
    BytecodeVM_EnableMenuAccess,   // 113
    BytecodeVM_EnableDragonRadar,   // 114
    BytecodeVM_SetActiveCharacterNoReset,   // 115
    BytecodeVM_ResetNonActiveSprites,   // 116
    BytecodeVM_RemoveRectFromMask2,   // 117
    BytecodeVM_AddRectToMask2,   // 118
    BytecodeVM_GetActiveEntityContext,   // 119
    BytecodeVM_SpawnEntityAtPoint_8016AB4,   // 120
    BytecodeVM_EntityCmd_8025ED4_1arg,   // 121
    BytecodeVM_DisableWorld,   // 122
    BytecodeVM_EnableWorld,   // 123
    BytecodeVM_SpawnSpriteAt,   // 124
    BytecodeVM_RunFullscreenSceneClearVram,   // 125
    BytecodeVM_PushActiveCharIsTransformed,   // 126
    BytecodeVM_SpawnMapEntity,   // 127
    BytecodeVM_SetPartyMemberFlag,   // 128
    BytecodeVM_PushSaveStatePtr,   // 129
    BytecodeVM_SpawnEntity_801C4B0,   // 130
    BytecodeVM_PushLevelUpEndStat,   // 131
    BytecodeVM_PushLevelUpPowStat,   // 132
    BytecodeVM_PushLevelUpStrStat,   // 133
    BytecodeVM_EntityCmd_8025550_2arg,   // 134
    BytecodeVM_EntityCmd_8025528_4arg,   // 135
    BytecodeVM_EntityCmd_8024C04_3arg,   // 136
    BytecodeVM_EntityCmd_802521C_1arg,   // 137
    BytecodeVM_EnterSleepMode,   // 138
    BytecodeVM_AddEXP,   // 139
    BytecodeVM_EntityCmd_8025500_15_1arg,   // 140
    BytecodeVM_RegisterScouterEntry,   // 141
    BytecodeVM_EntityMoveTowardEntity,   // 142
    BytecodeVM_PushEntityPosition,   // 143
    BytecodeVM_SetEntityPosition,   // 144
};

}  // namespace dbzlog2::vm
