// AUTO-GENERATED from OpCodes.csv + Legacy.wiki/Zenkai/opcodes/**/*.md signatures.
// Index -> (Name, Arity). Arity is the opcode's argument count as documented on its
// wiki page (i.e. how many values it pops off the VM stack / expects pushed before it).
// Regenerate by re-joining those two sources if opcode docs change.
//
// Genuinely-unresolved opcodes (still `sub_XXXXXX` in OpCodes.csv / documented as
// low-confidence "Unknown" under Legacy.wiki/Zenkai/opcodes/unknown/*.md, ~36 of them)
// are given a stable `op_unk<index>` name below instead of the raw ROM address, so
// they're visible and writable in Zenkai source at all (an address-shaped name is easy
// to typo and gives no hint it's the same opcode across scripts/sessions if the
// function ever gets renamed in IDA). The original sub_XXXXXX is kept on OriginalName
// purely for cross-referencing back to BytecodeVM_OpCodes.md / the wiki - it is NOT
// parseable/printable Zenkai source, only op_unk<index> is.
namespace Legacy.Zenkai
{
    internal static class OpcodeTable
    {
        internal record OpcodeInfo(int Index, string Name, int Arity, string? OriginalName = null);

        internal static readonly OpcodeInfo[] ByIndex = new OpcodeInfo[]
        {
            new(0, "PushAccumulator", 0),
            new(1, "PushGlobalVar0", 0),
            new(2, "PushGlobalVar1", 0),
            new(3, "PushGlobalVar2", 0),
            new(4, "PushScriptArg0", 0),
            new(5, "PushScriptArg1", 0),
            new(6, "PushScriptArg2", 0),
            new(7, "PushScriptArg3", 0),
            new(8, "PushCurrentWorld", 0),
            new(9, "PushCurrentArea", 0),
            new(10, "PushCurrentVariant", 0),
            new(11, "PushActiveCharIndex", 0),
            new(12, "PushActiveCharName", 0),
            new(13, "PushActiveCharHP", 0),
            new(14, "PushActiveCharMaxHP", 0),
            new(15, "PushActiveCharEP", 0),
            new(16, "PushActiveCharMaxEP", 0),
            new(17, "StackRand", 1),
            new(18, "StackRandChance", 1),
            new(19, "StackTestQuestFlag", 1),
            new(20, "StackTestQuestFlagNot", 1),
            new(21, "StackGetItemCount", 1),
            new(22, "StackGetCharLevel", 1),
            new(23, "StackTestPartyMemberFlag", 2),
            new(24, "DisableLayer", 1),
            new(25, "EnableLayer", 1),
            new(26, "PickUpItem", 1),
            new(27, "StackSetPartyFlag", 1),
            new(28, "StackClearPartyFlag", 1),
            new(29, "FindCharacterEntity", 1),
            new(30, "FindEntityByType", 1),
            new(31, "op_unk31", 3, "sub_800977A"),
            new(32, "CenterCameraOnChar", 1),
            new(33, "SetActiveEntity", 1),
            new(34, "SetMapRestoreFlag", 1),
            new(35, "LoadMapWithEntities", 5),
            new(36, "LoadMapNoEntities", 5),
            new(37, "RestoreMap", 0),
            new(38, "WarpToMapWithEntities", 5),
            new(39, "WarpToMapNoEntities", 5),
            new(40, "FadeOut", 1),
            new(41, "FadeFromWhite", 1),
            new(42, "FadeToWhite", 1),
            new(43, "op_unk43", 1, "sub_8009B94"),
            new(44, "op_unk44", 1, "sub_8009BBC"),
            new(45, "UploadSpritePalette", 0),
            new(46, "PlayAudio", 1),
            new(47, "StopAudio", 1),
            new(48, "StopAllAudio", 0),
            new(49, "PlayMusic", 1),
            new(50, "StopMusic", 0),
            new(51, "SpawnCharacterEntity", 3),
            new(52, "DespawnEntity", 1),
            new(53, "op_unk53", 3, "sub_8009D4A"),
            new(54, "MoveEntityToPosition", 3),
            new(55, "SetEntityFacing", 2),
            new(56, "SetEntityFollow", 2),
            new(57, "SetEntityAnimation", 2),
            new(58, "op_unk58", 2, "sub_800A044"),
            new(59, "Deprecated_CharacterSpecialAttack", 0),
            new(60, "op_unk60", 1, "sub_800A09A"),
            new(61, "Deprecated_CharacterFollow", 0),
            new(62, "op_unk62", 3, "sub_800A44E"),
            new(63, "BeginCommandBatch", 0),
            new(64, "CommitCommandBatch", 0),
            new(65, "PlayAudioBlocking", 1),
            new(66, "Deprecated_ShowImage", 0),
            new(67, "op_unk67", 0, "sub_800A622"),
            new(68, "op_unk68", 1, "sub_800A638"),
            new(69, "WaitFrames", 1),
            new(70, "SetActiveCharacter", 1),
            new(71, "SetCollisionRect", 4),
            new(72, "ClearCollisionRect", 0),
            new(73, "SetCharacterTransformation", 2),
            new(74, "ReloadMap", 0),
            new(75, "PushActiveCharNameUpper", 0),
            new(76, "RemoveItem", 1),
            new(77, "RemoveItems", 2),
            new(78, "op_unk78", 2, "sub_8009688"),
            new(79, "SetCharacterFlag_Bit0", 1),
            new(80, "SetCharacterFlag_Bit1", 1),
            new(81, "ClearCharacterFlag_Bit1", 1),
            new(82, "SetCharacterFlag_Bit5", 1),
            new(83, "SetCharacterFlag_Dynamic", 2),
            new(84, "TriggerMapEvent", 1),
            new(85, "FadeIn", 1),
            new(86, "SetPlayerVisible", 1),
            new(87, "SpawnItem", 3),
            new(88, "op_unk88", 0, "sub_800AC00"),
            new(89, "op_unk89", 4, "sub_8009D94"),
            new(90, "op_unk90", 3, "sub_800AB44"),
            new(91, "ClearCharacterFlag_Bit0", 1),
            new(92, "SpawnItem", 3),
            new(93, "op_unk93", 1, "sub_800A49A"),
            new(94, "op_unk94", 3, "sub_800A526"),
            new(95, "op_unk95", 1, "sub_800A572"),
            new(96, "op_unk96", 3, "sub_800A158"),
            new(97, "ReturnToTitleScreen", 0),
            new(98, "SetCharacterLevel", 2),
            new(99, "op_unk99", 4, "sub_800A210"),
            new(100, "op_unk100", 3, "sub_800A4DA"),
            new(101, "op_unk101", 2, "sub_800AC5C"),
            new(102, "op_unk102", 2, "sub_800ACAC"),
            new(103, "op_unk103", 4, "sub_800ACEA"),
            new(104, "DespawnCharacterAndRecordPosition", 2),
            new(105, "StackGetCharHP", 1),
            new(106, "StackGetCharEP", 1),
            new(107, "StackGetCharMaxHP", 1),
            new(108, "StackGetCharMaxEP", 1),
            new(109, "SetCharHP", 2),
            new(110, "SetCharEP", 2),
            new(111, "PlayAudioVolume", 2),
            new(112, "op_unk112", 2, "sub_800AE76"),
            new(113, "SetSaveExistsFlag_Bit2", 0),
            new(114, "SetSaveExistsFlag_Bit3", 0),
            new(115, "SetActiveCharacterNoReset", 1),
            new(116, "ResetNonActiveSprites", 0),
            new(117, "op_unk117", 4, "sub_800A850"),
            new(118, "op_unk118", 4, "sub_800A89E"),
            new(119, "GetActiveEntityContext", 0),
            new(120, "op_unk120", 2, "sub_800AD3E"),
            new(121, "op_unk121", 2, "sub_800A004"),
            new(122, "DisableWorld", 1),
            new(123, "EnableWorld", 1),
            new(124, "op_unk124", 3, "sub_800AEF0"),
            new(125, "op_unk125", 0, "sub_800AF44"),
            new(126, "PushActiveCharIsTransformed", 0),
            new(127, "SpawnMapEntity", 3),
            new(128, "SetQuestFlag", 1),
            new(129, "PushSaveStatePtr", 0),
            new(130, "op_unk130", 0, "sub_800AFD4"),
            new(131, "PushLevelUpStat1", 0),
            new(132, "PushLevelUpStat2", 0),
            new(133, "PushLevelUpStat3", 0),
            new(134, "op_unk134", 3, "sub_800A276"),
            new(135, "op_unk135", 4, "sub_800A2C2"),
            new(136, "op_unk136", 4, "sub_800A346"),
            new(137, "op_unk137", 2, "sub_800A3A2"),
            new(138, "EnterSleepMode", 0),
            new(139, "AddEXP", 2),
            new(140, "op_unk140", 2, "sub_8009F3C"),
            new(141, "RegisterScouterEntry", 1),
            new(142, "op_unk142", 3, "sub_800A1B4"),
            new(143, "PushEntityPosition", 1),
            new(144, "SetEntityPosition", 3),
        };

        internal static readonly Dictionary<int, OpcodeInfo> IndexMap = ByIndex.ToDictionary(o => o.Index);

        // Name is not unique (index 87 and 92 are both "SpawnItem", same handler address
        // per BytecodeVM_OpCodes.md) -- assembling by name uses the FIRST/lowest index.
        internal static readonly Dictionary<string, OpcodeInfo> NameMap = ByIndex
            .GroupBy(o => o.Name)
            .ToDictionary(g => g.Key, g => g.OrderBy(o => o.Index).First());
    }
}
