using System.Xml.Linq;

namespace Legacy.Zenkai
{
    /// <summary>
    /// Loads DBZKit/Legacy/OpcodeDocs.xml (generated by DBZKit/gen_opcode_xml.js from the
    /// same opcode data that produces the Legacy.wiki opcode pages) and exposes it for the
    /// editor's Ctrl+Space autocomplete list and call-tip hover hints.
    /// </summary>
    internal static class OpcodeDocs
    {
        internal record ParamDoc(string Name, string Description);
        internal record OpcodeDoc(string Name, string Summary, IReadOnlyList<ParamDoc> Params);

        private static readonly Dictionary<string, OpcodeDoc> _byName = Load();

        // Looks up by clean name first (e.g. "PushAccumulator"), falling back to the
        // original decompiled name (e.g. "sub_800977A") for op_unk<N> entries whose
        // OpcodeTable.Name doesn't match the doc's <member name>.
        internal static OpcodeDoc? Find(OpcodeTable.OpcodeInfo op)
        {
            if (_byName.TryGetValue(op.Name, out var doc)) return doc;
            if (op.OriginalName != null && _byName.TryGetValue(op.OriginalName, out doc)) return doc;
            return null;
        }

        internal static OpcodeDoc? Find(string name) => _byName.TryGetValue(name, out var doc) ? doc : null;

        private static Dictionary<string, OpcodeDoc> Load()
        {
            var result = new Dictionary<string, OpcodeDoc>();
            string path = Path.Combine(AppContext.BaseDirectory, "OpcodeDocs.xml");
            if (!File.Exists(path)) return result;

            try
            {
                var doc = XDocument.Load(path);
                foreach (var member in doc.Descendants("member"))
                {
                    string? name = member.Attribute("name")?.Value;
                    if (string.IsNullOrEmpty(name)) continue;

                    string summary = member.Element("summary")?.Value.Trim() ?? "";
                    var paramDocs = member.Elements("param")
                        .Select(p => new ParamDoc(p.Attribute("name")?.Value ?? "", p.Value.Trim()))
                        .ToList();

                    result[name] = new OpcodeDoc(name, summary, paramDocs);
                }
            }
            catch
            {
                // Missing/corrupt doc file shouldn't prevent the editor from working -- just no hints.
            }

            return result;
        }
    }
}
